services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql                # Database host set to the name of the db service
      DB_DATABASE: rest_quest_db # Database name (make sure this matches db service)
      DB_USERNAME: myuser        # MySQL user
      DB_PASSWORD: mypassword    # MySQL password
    ports:
      - "8020:8010"  # Expose app on port 8020
    volumes:
      - .:/var/www/html/rest-quest  # Mount app code into the container
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_quest_db # Name of the database to be created
      MYSQL_USER: myuser        # MySQL user
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"  # Expose MySQL on port 3307
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql

volumes:
  mysql-data:
